/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("glomers.kotlin-library-conventions")
    kotlin("plugin.serialization") version "1.9.22"
}

dependencies {
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0")
}
